### ISSUE TITLE
usage error: rehash failed to verify, something is wrong

### ISSUE THREAD

**Issue by ohwutup** [raggi/openssl-osx-ca#11]
```
/usr/local/Cellar/openssl-osx-ca/1.0.4/bin/openssl-osx-ca /usr/local/bin/brew
Usage error; try -help.
rehash failed to verify, something is wrong
check /var/folders/x2/3dkgdg3x4jlf3n10jtm45hj80000gn/T/openssl-osx-ca.vlHsIZLQ/cert.pem for problems
```

**Comment by raggi** [comment]
What version of openssl do you have installed?

**Comment by markeissler** [comment]
I'm seeing this with `openssl 0.9.8zd 8 Jan 2015`. Located in `/usr/bin/openssl`.

**Comment by ohwutup** [comment]
`OpenSSL 0.9.8zd 8 Jan 2015`

**Comment by eneagoe** [comment]
The 'Usage error; try -help'  message comes from openssl's `c_rehash` script. If you change in the openssl-osx-ca script this line
`tmpdir=$(/usr/bin/mktemp -d -t openssl-osx-ca)` to `tmpdir=$(/usr/bin/mktemp -d -t opensslosxca)` seems to fix the problem.

**Comment by raggi** [comment]
Holy crap that's old openssl.

Someone submitted an alternative patch for this in master already, but I'll do this too.

**Comment by raggi** [comment]
Would you all please test against master for me, I am not near a suitable machine right now.

**Comment by eneagoe** [comment]
Master looks fine now, no more `rehash` errors.

**Comment by markeissler** [comment]
Confirmed. Output looks good now.

**Comment by raggi** [comment]
1.0.5 is fixed.

**Comment by raggi** [comment]
I've also updated the brew tap, but again not from a machine I can test with. If you have a moment to verify it, I'd appreciate. Thanks so much!

**Comment by markeissler** [comment]
Looks good on my end. Thanks for fix!
