### ISSUE TITLE
does bundle rebuild happen only when changes where made on keychains?

### ISSUE THREAD

**Issue by ssbarnea** [raggi/openssl-osx-ca#15]
It seems that the documentation does to state if the bundle regeneration happens every hour or only this is checked every hour for changes in order to build it when changes are made.

This is quite an important detail because regeneration should happen only when needed in order to avoid already documented bugs due to switch of cert files (not to mention performance issues).

**Comment by raggi** [comment]
https://github.com/raggi/openssl-osx-ca/blob/master/bin/openssl-osx-ca#L73
